name: Release Chocolatey Package

on:
  push:
    branches:
      - main

env:
  CHOCO_PACKAGE_NAME: velero
  # publish packages to this url
  NUGET_SOURCE: https://push.chocolatey.org/

jobs:
  release-choco-package:
    # https://github.com/actions/virtual-environments
    runs-on: windows-2022
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create NuGet Package
        run: |
          cd ${{ env.CHOCO_PACKAGE_NAME }}
          choco pack -y

      - name: Test NuGet Package
        env:
          CHOCO_PACKAGE_NAME: ${{ env.CHOCO_PACKAGE_NAME }}
        run: ./../test.ps1
        working-directory: ${{ env.CHOCO_PACKAGE_NAME }}

      - name: Publish NuGet Package
        run: |
          cd ${{ env.CHOCO_PACKAGE_NAME }}

          # get version
          [xml]$spec = Get-Content ${{ env.CHOCO_PACKAGE_NAME }}.nuspec
          $version = $spec.package.metadata.version

          # set api key
          choco apikey --key ${{ secrets.CHOCOLATEY_API_KEY }} --source ${{ env.NUGET_SOURCE }}

          # push package
          Write-Output "Pushing version [$version] to [${{ env.NUGET_SOURCE }}]..."
          choco push -y ${{ env.CHOCO_PACKAGE_NAME }}.$($version).nupkg --source ${{ env.NUGET_SOURCE }}

      # https://github.com/actions/upload-artifact
      - uses: actions/upload-artifact@v4
        with:
          name: velero-chocolatey-package
          path: "**/*.nupkg"
