name: Test Chocolatey Package

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, converted_to_draft]
  workflow_dispatch:

env:
  CHOCO_PACKAGE_NAME: velero
  # publish packages to this url
  NUGET_SOURCE: https://push.chocolatey.org/

jobs:
  test-choco-package:
    # https://github.com/actions/virtual-environments
    runs-on: windows-2022
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create NuGet Package
        run: |
          cd ${{ env.CHOCO_PACKAGE_NAME }}
          choco pack -y

      - name: Test NuGet Package
        env:
          CHOCO_PACKAGE_NAME: ${{ env.CHOCO_PACKAGE_NAME }}
        run: ./../test.ps1
        working-directory: ${{ env.CHOCO_PACKAGE_NAME }}
